version: '3.8'
services:
  web:
    image: nginx:1.25.3
    container_name: nginx-web
    volumes:
    - ./content:/usr/share/nginx/html
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./config/conf.d:/etc/nginx/conf.d
    networks:
      - elastic
    ports:
    - "8181:80"